schemaVersion: 2.2.0
metadata:
  name: java-spring-petclinic

# projects:
#   - name: nodejs-devfile-test
#     git:
#       remotes:
#         origin: https://github.com/vitaliy-guliy/nodejs-devfile-test.git

#   - name: lombok-project-sample
#     git:
#       remotes:
#         origin: https://github.com/vitaliy-guliy/lombok-project-sample.git

components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryLimit: 1G
      mountSources: true
